name: Anpassung
description: Änderungen bzw. Anpassung von bestehenden Features, z. B. Textänderungen, etc.
title: "[Anpassung]: "
labels: ["anpassung"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Änderungen bzw. Anpassung von bestehenden Features, z. B. Textänderungen, etc.
  - type: textarea
    id: description
    attributes:
      label: Beschreibung der Anpassung
      description: Was soll angepasst oder verbessert werden?
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Ziel / Grund / Nutzen
      description: Warum sollte diese Anpassung stattfinden?
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Betroffene Bereiche / Auswirkungen
      description: Was ist betroffen? Gibt es mögliche Abhängigkeiten, Risiken oder Nebeneffekte?
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Lösungsvorschlag (optional)
      description: Hast du schon eine Idee, wie das umgesetzt werden kann?
    validations:
      required: false
  - type: textarea
    id: appendix
    attributes:
      label: Anhänge / Ergänzungen (optional)
      description: Screenshots, Skizzen, Links, etc.
    validations:
      required: false
 
