name: Bug
description: Melde einen Fehler.
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Danke, dass du einen Bug meldest! Bitte fülle die Felder für eine schnelle Bearbeitung Aus.
  - type: textarea
    id: what-happened
    attributes:
      label: Was ist passiert?
      description: Beschreibe den Fehler sowie das erwartete Verhalten.
      placeholder: Beschreibe das beobachtete und das erwartete Verhalten.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Schritte zur Reproduktion
      description: Wie kann der Fehler reproduziert werden? Schritt für Schritt.
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Erwartetes Verhalten
      description: Wie sollte es sich verhalten?
    validations:
      required: false
  - type: textarea
    id: actual-behavior
    attributes:
      label: Tatsächliches Verhalten
      description: Was passiert stattdessen?
    validations:
      required: false
  - type: input
    id: version-build
    attributes:
      label: Version / Build
      description: Welche Softwareversion ist betroffen (falls bekannt)?
      placeholder: z.B. 1.2.3, Build abcdef
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevante Logs (optional)
      description: Kopiere und füge relevante Fehlermeldungen oder Logs ein.
      render: shell
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Anhang (optional)
      description: Füge hier Links zu relevanten Dateien oder Screenshots ein. Alternativ kannst du Dateien nach dem Erstellen des Tickets per Drag & Drop direkt ins Kommentarfeld hochladen.
    validations:
      required: false
