name: User Story
description: Erstelle eine neue User Story oder schlage eine Funktion vor.
title: "[User Story]: "
labels: ["user story", "feature"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        **Bitte trage alle relevanten Informationen für deine User Story ein. Hilfetexte und Beispiele unterstützen dich beim Ausfüllen.**
  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Beschreibe die User Story nach dem Format "Als <Rolle> möchte ich <Ziel>, um <Nutzen> zu erreichen."
      placeholder: |
        Beispiel:
        Als Kund:in möchte ich meine Bestellung stornieren können,
        um flexibel auf Änderungen reagieren zu können.
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Akzeptanzkriterien
      description: Definiere die Akzeptanzkriterien im Format "GIVEN WHEN THEN".  
      placeholder: |
        Beispiel:
        - GIVEN eine bestätigte Bestellung
        - WHEN der Stornieren-Button geklickt wird
        - THEN wird die Bestellung storniert und eine Bestätigung angezeigt
    validations:
      required: true
  - type: input
    id: design-link
    attributes:
      label: Link zu Designs
      description: Füge, falls vorhanden, einen Link zu den Designs hinzu.
      placeholder: https://www.figma.com/file/123456/Beispiel-Design
    validations:
      required: false
  - type: textarea
    id: implementation-details
    attributes:
      label: Implementierungsdetails
      description: Hinweise zur technischen Umsetzung, Architektur, API-Endpunkte, etc.
      placeholder: |
        Beispiel:
        - Backend-Endpunkt "/api/orders/{id}/cancel" notwendig.
        - Fehlerbehandlung - Bestellung kann nur storniert werden, wenn Status = 'Offen'.
        - Event zur Benachrichtigung an UI und E-Mail-System.
    validations:
      required: false
  - type: textarea
    id: risks-assumptions
    attributes:
      label: Risiken & Annahmen
      description: Welche Risiken, offenen Fragen oder Annahmen bestehen?  
      placeholder: |
        Beispiel
        - Risiko - Nutzer:innen könnten versehentlich Bestellungen stornieren.
        - Annahme - Nur Bestellungen mit Status 'Offen' sind stornierbar.
        - Noch zu klären - Auswirkungen auf das Lagerverwaltungssystem.
    validations:
      required: false
