name: Label Issue High Prio
on:
  issues:
    types: [opened]

jobs:
  label-high-prio:
    runs-on: ubuntu-latest
    if: github.event.issue.title != '' # Optional: nur Issues mit Titel
    steps:
      # Schritt 1: Issue Title parsen (geht nur f端r Issue-Forms durch das JSON body)
      - name: Check for bug type and priority
        id: check_priority
        uses: actions/github-script@v7
        with:
          script: |
            // Pr端fe ob es ein Bug ist (z. B. im Titel)
            const isBug = context.payload.issue.title.toLowerCase().includes('[bug]');
            if (!isBug) {
              return;
            }

            // Extrahiere die "priority" aus dem Issue-Body (das ist als JSON im body bei Issue Forms verf端gbar)
            const body = context.payload.issue.body;
            // Einfacher Regex-Parser f端r das "priority:" Feld
            const match = body.match(/priority:\s*(\w+)/i);
            if (match && match[1].toLowerCase() === "high") {
              github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                labels: ['prio high']
              });
            }
