name: Set High Prio Label for Bug Issues

on:
  issues:
    types: [opened]

jobs:
  add_high_prio_label:
    runs-on: ubuntu-latest
    steps:
      - name: Add "prio high" label if bug and high prio
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const title = issue.title.toLowerCase();
            const body = issue.body || '';

            // Pr체fe, ob als Bug markiert (z.B. [Bug] am Anfang des Titels)
            if (!title.includes('[bug]')) {
              return; // Kein Bug: Nichts tun
            }

            // Suche "Priorit채t" Section (deutsch, Markdown-Form)
            // Beispiel: ### Priorit채t\n\nhigh
            const prioMatch = body.match(/### Priorit[a채]t\s*\n+\s*(\w+)/i);

            if (prioMatch && prioMatch[1].toLowerCase() === 'high') {
              console.log('prio high detected, label will be added');
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: ['prio high']
              });
            } else {
              console.log('priority not high or field not found');
            }
