name: Set High Prio Label for Bug Issues

on:
  issues:
    types: [opened]

permissions:
  issues: write   # WICHTIG: Erlaubt das Hinzufügen von Labels zu Issues

jobs:
  add_high_prio_label:
    runs-on: ubuntu-latest
    steps:
      - name: Add "prio high" label if Bug and Priority = high
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const title = issue.title.toLowerCase();
            const body = issue.body || '';

            // Prüft, ob das Issue ein Bug ist (Titel enthält '[Bug]')
            if (!title.includes('[bug]')) return;

            // Sucht die Markdown-Section für Priorität und den Wert darunter
            // Erlaubt auch Priorität mit Umlaut oder AE Schreibweise
            const prioMatch = body.match(/### Priorit[aä]t\s*\n+\s*(\w+)/i);

            // Wenn Priorität "high" ist, wird das Label gesetzt
            if (prioMatch && prioMatch[1].toLowerCase() === 'high') {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: ['prio high']
              });
            }
